# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BalkanidCli < Formula
  desc "Balkan ID CLI is a command line interface to extract entitlements of various platforms."
  homepage "https://www.balkan.id/"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.2/balkanid-cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "2d95c8eb391604b393c8c19980185ca5821eadf6e8fd889cd821879d90c17616"

      def install
        bin.install "balkanid-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.2/balkanid-cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "1dbc1812dbb445aa2d3f67904e43126506a68632c5021361cc1035502e712d77"

      def install
        bin.install "balkanid-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.2/balkanid-cli_0.2.2_linux_arm64.tar.gz"
      sha256 "629c2a226bce2bd0d9d5e1726b0aa9f89837729ed2a5f47d84f7206f93f3792f"

      def install
        bin.install "balkanid-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.2/balkanid-cli_0.2.2_linux_amd64.tar.gz"
      sha256 "09d63d9a1edae4a2f0619b1df8e430ebae37ccea7eff0f48971aa844440c8db2"

      def install
        bin.install "balkanid-cli"
      end
    end
  end
end
