# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BalkanidCli < Formula
  desc "Balkan ID CLI is a command line interface to extract entitlements of various platforms."
  homepage "https://www.balkan.id/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.0/balkanid-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "c013c3e90bd664cc018d197c012b93eb54bd07e4e5dff0fae2693117e74f8b85"

      def install
        bin.install "balkanid-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.0/balkanid-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "f2e267d21e9ec32028c49589d9bb55f4453966ac230b06a47c88b166c6a3265a"

      def install
        bin.install "balkanid-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.0/balkanid-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "75b709e09676aa3c54d56fb78053d7f38895b60280dd265b10e6274cb3188f6a"

      def install
        bin.install "balkanid-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BalkanID/homebrew-cli/releases/download/v0.2.0/balkanid-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "49b5cb23014fcfd358de07761d29dd844bdb4df27f2e889ee3c550e58e314b9e"

      def install
        bin.install "balkanid-cli"
      end
    end
  end
end
